name: GitHub Actions for GCP

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
        
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      #Substitute production appsettings entries to appsettings json file
      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: '*/appsettings.json'
        env:
          ConnectionStrings.BethanysPieShopDbContextConnection: ${{ secrets.GCP_DB_CONNECTION_STRING }}

      #- id: 'auth'
      #  name: 'Authenticate to Google Cloud'
      #  uses: 'google-github-actions/auth@v1'
      #  with:
      #    credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          
      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v1
        with:
          #deliverables: app.yaml
          version: v1
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_CREDENTIALS }}
